# Generated by Django 4.2.3 on 2023-08-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=45)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_name', to='users.user')),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_name2', to='users.user')),
                ('users', models.ManyToManyField(to='users.user')),
            ],
        ),
    ]
