# Generated by Django 4.2.3 on 2023-10-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_sessiongame_protected_alter_sessiongame_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiongame',
            name='users',
        ),
    ]
