# Generated by Django 5.1.1 on 2024-12-03 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0005_customuser_is_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True,
                                                        on_delete=django.db.models.deletion.CASCADE,
                                                        parent_link=True,
                                                        primary_key=True,
                                                        serialize=False,
                                                        to=settings.AUTH_USER_MODEL)),
                ('personality',
                 models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Bot User',
                'verbose_name_plural': 'Bot Users',
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
