# Generated by Django 5.1.1 on 2024-11-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_messages', '0003_systemnotice'),
        ('games', '0005_set_default_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotice',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
