# Generated by Django 5.1.1 on 2024-11-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_games_abandoned_customuser_games_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rating',
            field=models.FloatField(default=1000),
        ),
    ]
