# Generated by Django 5.1.1 on 2024-11-05 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='games_played',
        ),
    ]
