# Generated by Django 5.1.1 on 2024-12-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
