# Generated by Django 5.1.1 on 2024-09-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='active_player',
            field=models.IntegerField(default=1),
        ),
    ]
