# Generated by Django 5.1.1 on 2024-11-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_archived_for_p1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='is_archived_for_p2',
            field=models.BooleanField(default=False),
        ),
    ]
